---
- set_fact:
    apt_packages: "{{ __apt_packages|list }}"
  when: apt_packages|default(None) == None

- copy:
    src: "{{ distribution_codename }}/"
    dest: /
    mode: preserve

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-dev-hpc"
     package_depends: "{{ apt_packages }}"

- shell: "/usr/local/bin/{{ item }}"
  loop:
  - make_install_flame.sh
  - make_install_elemental.sh
  - make_install_fmt.sh

- set_fact:
    apt_packages: !!null
